### ISSUE TITLE
resolve() is always strict with Python 2.7 on Windows

### ISSUE THREAD

**Issue by matthew16550** [mcmtroffaes/pathlib2#45]
I'm using pathlib2 version 2.3.2.

On Windows with Python 2.7 the strict=False option has no effect:
```
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pathlib2
>>> pathlib2.Path('foo').resolve(False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Python27\lib\site-packages\pathlib2\__init__.py", line 1343, in resolve
    self.stat()
  File "c:\Python27\lib\site-packages\pathlib2\__init__.py", line 1356, in stat
    return self._accessor.stat(self)
  File "c:\Python27\lib\site-packages\pathlib2\__init__.py", line 541, in wrapped
    return strfunc(str(pathobj), *args)
WindowsError: [Error 2] The system cannot find the file specified: 'foo'
```

On OSX with Python 2.7 it works ok:
```
Python 2.7.15 (default, Jun 17 2018, 13:05:56)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pathlib2
>>> pathlib2.Path('/foo').resolve(False)
PosixPath('/foo')
```

And on Windows with Python 3.7 it works ok:
```
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pathlib2
>>> pathlib2.Path('foo').resolve(False)
WindowsPath('foo')
```

**Comment by mcmtroffaes** [comment]
I think this is the same as issue #47 - let's discuss further there.
